package net.coderazzi.glasspane.test;

import java.util.Properties;

import javax.swing.table.AbstractTableModel;

import net.coderazzi.glasspane.LabelGlassPane;

/**
 * The image busy.gif was downloaded using the nice 
 * <a href='http://www.ajaxload.info/'>ajax loading gif generator</a>
 * @author coderazzi (lu@coderazzi.net)
 */
public class FrameExample extends javax.swing.JFrame {
	
    /** Creates new form FrameExample */
    public FrameExample() {
        initComponents();
        System.setProperty(net.coderazzi.glasspane.LabelGlassPane.GLASS_MESSAGE_ICON_PROPERTY, "/net/coderazzi/glasspane/test/busy.gif");
        System.setProperty(net.coderazzi.glasspane.GlassedPane.GLASS_CLASS_PROPERTY, LabelGlassPane.class.getName());
        setSize(600, 550);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glassCheckbox = new javax.swing.JCheckBox();
        jSplitPane1 = new javax.swing.JSplitPane();
        glassPane = new net.coderazzi.glasspane.GlassedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GlassedPane example");

        glassCheckbox.setText("glass active");
        glassCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                glassCheckboxItemStateChanged(evt);
            }
        });
        getContentPane().add(glassCheckbox, java.awt.BorderLayout.NORTH);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);

        glassPane.getContentPane().setLayout(new java.awt.BorderLayout());

        table1.setModel(new PropertiesTableModel());
        jScrollPane2.setViewportView(table1);

        glassPane.getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(glassPane);

        table2.setModel(new PropertiesTableModel());
        jScrollPane1.setViewportView(table2);

        jSplitPane1.setRightComponent(jScrollPane1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void glassCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_glassCheckboxItemStateChanged
        // TODO add your handling code here:
        glassPane.getGlassPane().setVisible(evt.getStateChange()==java.awt.event.ItemEvent.SELECTED);
    }//GEN-LAST:event_glassCheckboxItemStateChanged

	class PropertiesTableModel extends AbstractTableModel{
		Properties properties = System.getProperties();
		Object keys[] = properties.keySet().toArray();
		@Override
		public int getColumnCount() {
			return 2;
		}
		@Override
		public int getRowCount() {
			return keys.length;
		}
		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {
			Object key = keys[rowIndex];
			return columnIndex==0? key : properties.get(key);
		}
		@Override
		public String getColumnName(int column) {
			return column==0? "Property" : "Value";
		}
	}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameExample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox glassCheckbox;
    private net.coderazzi.glasspane.GlassedPane glassPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables

}
